# -------------------------
# synku release: simple-app
# -------------------------
---
# synku component: simple-app-webapp
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nginx:alpine
          ports:
            - containerPort: 80
          name: simple-app-webapp
    metadata:
      labels:
        app.kubernetes.io/name: simple-app
        app.kubernetes.io/component: simple-app-webapp
        app.kubernetes.io/managed-by: synku
        app.kubernetes.io/version: 1.0.0
        synku/match: simple-app-webapp
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-app
      app.kubernetes.io/component: simple-app-webapp
      app.kubernetes.io/managed-by: synku
      app.kubernetes.io/version: 1.0.0
      synku/match: simple-app-webapp
metadata:
  name: simple-app-webapp
  labels:
    app.kubernetes.io/name: simple-app
    app.kubernetes.io/component: simple-app-webapp
    app.kubernetes.io/managed-by: synku
    app.kubernetes.io/version: 1.0.0

---
# synku component: simple-app-webapp
apiVersion: v1
kind: Service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
metadata:
  name: simple-app-webapp
  labels:
    app.kubernetes.io/name: simple-app
    app.kubernetes.io/component: simple-app-webapp
    app.kubernetes.io/managed-by: synku
    app.kubernetes.io/version: 1.0.0
