# example-backend-queue
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
      containers:
        - image: mqtt
metadata:
  name: example-backend-queue
  labels:
    synku/release: example
    synku/component: example-backend-queue

---
# example-backend-worker
apiVersion: apps/v1
kind: DaemonSet
spec:
  template:
    spec:
      containers:
        - image: custom-worker
metadata:
  name: example-backend-worker
  labels:
    synku/release: example
    synku/component: example-backend-worker

---
# example-backend-api
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - image: custom-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
  replicas: 2
  selector:
    matchLabels:
      synku/release: example
      synku/component: example-backend-api
metadata:
  name: example-backend-api
  labels:
    synku/release: example
    synku/component: example-backend-api

---
# example-backend-api
apiVersion: v1
kind: Service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    synku/release: example
    synku/component: example-backend-api
metadata:
  name: example-backend-api
  labels:
    synku/release: example
    synku/component: example-backend-api

---
# example-ui
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - image: custom-ui:latest
          ports:
            - containerPort: 3000
          env:
            - name: HTTP_PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
  replicas: 2
  selector:
    matchLabels:
      synku/release: example
      synku/component: example-ui
metadata:
  name: undefinedexample-ui
  labels:
    synku/release: example
    synku/component: example-ui

---
# example-ui
apiVersion: v1
kind: Service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    synku/release: example
    synku/component: example-ui
metadata:
  name: undefinedexample-ui
  labels:
    synku/release: example
    synku/component: example-ui

