# example-ui
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    static: annotation
  labels:
    static: label
    synku/component: example-ui
    synku/release: example
  name: example-ui
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      example-component: example-ui
      example-release: example
  template:
    metadata:
      labels:
        synku/app: example-ui
    spec:
      containers:
        - image: custom-ui:latest
          name: ui
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
# example-ui
apiVersion: v1
kind: Service
metadata:
  annotations:
    static: annotation
  labels:
    static: label
    synku/component: example-ui
    synku/release: example
  name: example-ui
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    example-component: example-ui
    example-release: example
  type: ClusterIP

---
# example-backend-queue
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    static: annotation
  labels:
    static: label
    synku/component: example-backend-queue
    synku/release: example
  name: example-backend-queue
spec:
  selector:
    matchLabels:
      example-component: example-backend-queue
      example-release: example
  serviceName: example-backend-queue
  template:
    spec:
      containers:
        - image: mqtt
          name: queue
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
# example-backend-queue
apiVersion: v1
kind: Service
metadata:
  annotations:
    static: annotation
  labels:
    static: label
    synku/component: example-backend-queue
    synku/release: example
  name: example-backend-queue
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    example-component: example-backend-queue
    example-release: example
  type: ClusterIP

---
# example-backend-worker
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    static: annotation
  labels:
    static: label
    synku/component: example-backend-worker
    synku/release: example
  name: example-backend-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      example-component: example-backend-worker
      example-release: example
  template:
    spec:
      containers:
        - image: custom-worker
          name: worker
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
# example-backend-api
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    static: annotation
  labels:
    static: label
    synku/component: example-backend-api
    synku/release: example
  name: example-backend-api
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      example-component: example-backend-api
      example-release: example
  template:
    metadata:
      labels:
        synku/app: example-backend-api
    spec:
      containers:
        - image: custom-api:latest
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
# example-backend-api
apiVersion: v1
kind: Service
metadata:
  annotations:
    static: annotation
  labels:
    static: label
    synku/component: example-backend-api
    synku/release: example
  name: example-backend-api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    example-component: example-backend-api
    example-release: example
  type: ClusterIP
